function english(){
    var data=[]
var data=[
   '<!DOCTYPE html><html lang="en"> <head><meta charset="utf-8"><title>XIX</title><meta content="width=device-width,initial-scale=1.0" name="viewport"><meta content="" name="keywords"> <meta content="xix is the besplatforme of web disigner and Android" name="description"><link href="img/favicon.png" rel="icon"><link href="img/apple-touch-icon.png" rel="apple-touch-icon"><!-- Google Fonts --><link href=" rel="stylesheet"><link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet"><link href="lib/animate/animate.min.css" rel="stylesheet"><link href="lib/font-awesome/css/font-awesome.min.css" rel="stylesheet"> <link href="lib/ionicons/css/ionicons.min.css" rel="stylesheet"><link href="lib/magnific-popup/magnific-popup.css" rel="stylesheet"><!-- Main Stylesheet File --><link href="css/style.css" rel="stylesheet"></head><body> <header id="header"><div class="container"> <div id="logo" class="pull-left"><h1><a href="#intro" class="scrollto">XIX</a></h1></div>'+
 '<nav id="nav-menu-container"> <ul class="nav-menu"><li class="menu-active"><a href="#intro" id="a">Home</a></li><li><small>language</small><br><a id="b" href="#about" onclick="english()">Anglais</a></li> <li><a href="#features" id="c">Creativity</a></li> <ul> <li><a href="#">Upload</a></li> <li class="menu-has-children"><a href="#">export</a></ul> </nav><!-- #nav-menu-container --></div></header><!-- #header --> <section id="intro"><br><div class="intro-text"> <h2>Welcome to XIX</h2>  <p>imagine. create. publish.</p> <a href="#about" class="btn-get-started scrollto">Start</a><a href="#" onclick="test()" id="test" class="btn-get-started scrollto">creations</a> <a href="#" onclick="playNOW()" class="btn-get-started scrollto">PlayNow</a><br> <script> function test(){ window.location="xix_ide/index.html";} </script> </div>'+
    
       ' <div class="product-screens"><div class="product-screen-1 wow fadeInUp" data-wow-delay="0.4s" data-wow-duration="0.6s">'+'</div> <div class="product-screen-2 wow fadeInUp" data-wow-delay="0.2s" data-wow-duration="0.6s"> </div></div></section> <main id="main"><footer id="footer"><div class="container"><div class="row"><div class="col-lg-6 text-lg-left text-center"><div class="copyright">&copy; Copyright 2020 <strong>XIX</strong>. All Rights Reserved</div><div class="credits"> Designed by <a href="https://bit.ly/xixforme">Zanke Traore</a> </div></div><div class="col-lg-6"> <nav class="footer-links text-lg-right text-center pt-2 pt-lg-0"> <a href="#intro" class="scrollto">Home</a><a href="lib/web/about.html" target="_blank">About</a><a href="Avilon/account/index.html">Creer un compte</a><a href="#">Terms d utilisation</a> </nav></div></div> </div> </footer><a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a> <script src="lib/jquery/jquery.min.js"></script> <script src="lib/jquery/jquery-migrate.min.js"></script> <script src="lib/bootstrap/js/bootstrap.bundle.min.js"></script> <script src="lib/easing/easing.min.js"></script><script src="lib/wow/wow.min.js"></script><script src="lib/superfish/hoverIntent.js"></script><script src="lib/superfish/superfish.min.js"></script><script src="lib/magnific-popup/magnific-popup.min.js"></script><script src="contactform/contactform.js"></script> <script src="js/main.js"></script><script src="js/initialize_xix.js"></script> </body></html>'];//the body content

var body=document.getElementById('body');
body.innerHTML=data;
    }
    typeof '*/*';
    StorageManager.apply(body);
    //the function to apply system initialize on fetch method
